@WebApiHost = http://localhost:5555

###
GET {{{WebApiHost}}}/people
###
GET {{WebApiHost}}/people/1
###
POST {{WebApiHost}}/people
Content-Type: application/json

{
    "firstName": "Andrew",
    "lastName": "Pipo",
    "nickName": "Pipo"
}

###
PUT {{WebApiHost}}/people/1
Content-Type: application/json

{
    "personId": 1,
    "firstName": "Andrew",
    "lastName": "Pipo",
    "nickName": "Hippo"
}

###
DELETE {{WebApiHost}}/people/1
